// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/jamesrr39/genny

// +build x,y z

package buildtags

import "fmt"

func intPrint(t int) {
	fmt.Println(t)
}
